SimpleCrud/SimpleCrud/Models/Patient.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SimpleCrud.Models
{
    public class Patient
    {
        public int Id { get; set; }

        public string PatientName { get; set; }

        public int Height { get; set; }

        public DateTime DOB { get; set; }
    }
}

SimpleCrud/SimpleCrud/Controllers/CrudController.cs
using SimpleCrud.Models;
using SimpleCrud.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SimpleCrud.Controllers
{
    public class CrudController : Controller
    {
        PatientRepository _repository;

        public CrudController()
        {
            _repository = new PatientRepository();
        }

        //
        // GET: /Crud/
        public ActionResult Index()
        {
            return View("CrudView");
        }

        public JsonResult GetAllRecords()
        {
            return Json(new { Result = "OK", Records = _repository.GetAllRecords() });
        }

        public JsonResult Update(Patient patient)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return Json(new { Result = "ERROR", Message = "Form is not valid! Please correct it and try again." });
                }

                _repository.Update(patient);

                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        public JsonResult Insert(Patient patient)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return Json(new { Result = "ERROR", Message = "Form is not valid! Please correct it and try again." });
                }

                patient.Id = _repository.Insert(patient);

                return Json(new { Result = "OK", Record = patient });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }


        public JsonResult Delete(int id)
        {
            try
            {
                _repository.Delete(id);
                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

    }
}

SimpleCrud/SimpleCrud/Views/Crud/CrudView.cshtml
@{
    ViewBag.Title = "CRUD App";
}

<div id="Container"></div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#Container').jtable({
            title: 'Person Name',
            paging: false,
            actions: {
                listAction: '@Url.Action("GetAllRecords")',
                updateAction: '@Url.Action("Update")',
                createAction: '@Url.Action("Insert")',
                deleteAction: '@Url.Action("Delete")'
            },
            fields: {
                Id: {
                    key: true,
                    create: false,
                    edit: false,
                    list: false
                },
                PatientName: {
                    title: 'Person Name',
                    width: '23%'
                },
                Height: {
                    title: 'Height(in cm)',
                },
                DOB: {
                    title: 'Birth date',
                    width: '15%',
                    type: 'date',
                    displayFormat: 'yy-mm-dd'
                }
            }
        });
        //Load patient list from server
        $('#Container').jtable('load');
    });
</script>

SimpleCrud/SimpleCrud/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
    <link href="~/Scripts/jtable/themes/metro/lightgray/jtable.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/jquery-1.9.1.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.9.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jtable/jquery.jtable.min.js"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CRUD App V1.0", "Index", "Crud", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - CRUD App Inc</p>
        </footer>
    </div>


</body>
</html>